name: Deploy React Frontend to GitHub Pages

on:
  push:
    branches: [main] # Trigger workflow on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use the latest LTS version of Node.js

      - name: List files (before cd)
        run: ls -la  # List all files in the current directory (root)

      - name: Change directory to frontend
        run: cd frontend

      - name: Verify current directory
        run: pwd

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build # The folder containing your React build output (usually 'build' or 'dist')
          branch: gh-pages # The branch to deploy to (must match your GitHub Pages source branch)
          repository-name: ${{ github.repository }} # Optional, but good practice to be explicit
          token: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN secret