name: Docker Image CI

on: # trigger even for every pull request and commit on any branch
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login in to Dock Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.emmamelkumian }}
          password: ${{ secrets.dckr_pat_yfjD6bvUuey2TVAdBNf-7Qejrqw }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: emmamelkumian/emailessence:${{ github.ref_name }}
          push: true

